# Generated by Django 5.1.5 on 2025-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0002_alter_studentresponse_ai_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
