# Generated by Django 5.1.5 on 2025-03-15 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0003_studentresponse_evaluated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='time_limit',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # ✅ Removed default
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
