# Generated by Django 5.1.5 on 2025-03-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0004_airesponse_time_limit_generatedquestion_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
