# Generated by Django 5.0.6 on 2024-06-10 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0005_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('number_of_questions', models.IntegerField()),
                ('prompt_instructions', models.TextField()),
                ('generated_questions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
