# Generated by Django 5.1.5 on 2025-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0005_remove_airesponse_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='time_limit',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
