# Generated by Django 5.1.5 on 2025-06-05 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0006_airesponse_time_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='experiment_videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiment_images/')),
                ('manual', models.FileField(upload_to='experiment_manuals/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('data', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='experiment_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.virtualexperiment')),
            ],
        ),
    ]
