# Generated by Django 5.1.5 on 2025-06-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0007_virtualexperiment_experimentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualexperiment',
            name='image',
        ),
        migrations.CreateModel(
            name='ExperimentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiment_images/')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='QuestionBank.virtualexperiment')),
            ],
        ),
    ]
