# Generated by Django 5.0.6 on 2024-06-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0008_generatedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='generated_questions',
            new_name='AIResponse',
        ),
        migrations.DeleteModel(
            name='GeneratedQuestions',
        ),
    ]
