# Generated by Django 5.1.5 on 2025-06-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0008_remove_virtualexperiment_image_experimentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('marks', models.PositiveIntegerField(default=1)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuestionBank.virtualexperiment')),
            ],
        ),
    ]
