# Generated by Django 5.0.6 on 2024-06-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0009_rename_generated_questions_airesponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('ai_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.airesponse')),
            ],
        ),
    ]
