# Generated by Django 5.1.5 on 2025-06-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0010_virtualexperiment_requires_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.experimentquestion')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QuestionBank.experimentreport')),
            ],
        ),
    ]
