# Generated by Django 5.0.6 on 2024-06-13 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0010_studentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
