# Generated by Django 5.1.5 on 2025-06-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0011_experimentanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualexperiment',
            options={'verbose_name': 'Virtual Experiment', 'verbose_name_plural': 'Virtual Experiments'},
        ),
        migrations.RemoveField(
            model_name='virtualexperiment',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='virtualexperiment',
            name='video',
        ),
        migrations.AddField(
            model_name='virtualexperiment',
            name='apparatus',
            field=models.TextField(blank=True, default='No apparatus listed.'),
        ),
        migrations.AddField(
            model_name='virtualexperiment',
            name='method_summary',
            field=models.TextField(blank=True, help_text='Optional overview of the procedure.'),
        ),
        migrations.AddField(
            model_name='virtualexperiment',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualexperiment',
            name='theory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualexperiment',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApparatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apparatus_images/')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.virtualexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='step_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='step_videos/')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.virtualexperiment')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='TheoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='theory_images/')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.virtualexperiment')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperimentImage',
        ),
    ]
