# Generated by Django 5.1.5 on 2025-06-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0012_alter_virtualexperiment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualexperiment',
            name='apparatus',
        ),
        migrations.RemoveField(
            model_name='virtualexperiment',
            name='description',
        ),
        migrations.AddField(
            model_name='experimentstep',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional external video link (e.g., Google Drive/YouTube)', null=True),
        ),
        migrations.CreateModel(
            name='ApparatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='apparatus_items/')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apparatus_items', to='QuestionBank.virtualexperiment')),
            ],
        ),
        migrations.DeleteModel(
            name='ApparatusImage',
        ),
    ]
