# Generated by Django 5.0.6 on 2024-06-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0012_remove_studentresponse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='generated_questions',
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='prompt_instructions',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='evaluator_ai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generated_responses', to='QuestionBank.evaluatorai'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('ai_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuestionBank.airesponse')),
            ],
        ),
    ]
