# Generated by Django 5.0.6 on 2024-06-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0013_remove_airesponse_generated_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='question_index',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.generatedquestion'),
            preserve_default=False,
        ),
    ]
