# Generated by Django 4.2 on 2025-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0013_remove_virtualexperiment_apparatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
