# Generated by Django 5.0.6 on 2024-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0014_remove_studentresponse_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
