# Generated by Django 4.2 on 2025-06-17 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0014_theoryimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Write observations or draft data here.')),
                ('draft_image', models.ImageField(blank=True, null=True, upload_to='drafts/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionBank.virtualexperiment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('experiment', 'student')},
            },
        ),
    ]
