# Generated by Django 4.2 on 2025-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0015_experimentdraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdraft',
            name='draft_image',
        ),
        migrations.RemoveField(
            model_name='experimentdraft',
            name='notes',
        ),
        migrations.AddField(
            model_name='experimentdraft',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdraft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='draft_uploads/'),
        ),
        migrations.AddField(
            model_name='experimentdraft',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
