# Generated by Django 5.0.6 on 2024-07-02 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0015_studentresponse_evaluated_studentresponse_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
