# Generated by Django 5.0.6 on 2024-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0016_studentresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
