# Generated by Django 4.2 on 2025-06-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0016_remove_experimentdraft_draft_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentreport',
            name='draft_used',
            field=models.OneToOneField(blank=True, help_text='The draft that was used to submit this report (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_report', to='QuestionBank.experimentdraft'),
        ),
    ]
