# Generated by Django 4.2 on 2025-06-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0017_experimentreport_draft_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentreport',
            name='apparatus_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='data_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='group_members',
            field=models.TextField(blank=True, help_text='List of group members', null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='theory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
