# Generated by Django 4.2 on 2025-06-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0018_experimentreport_apparatus_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentreport',
            name='apparatus_scope',
            field=models.TextField(blank=True, null=True, verbose_name='Apparatus/Scope'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='data',
            field=models.TextField(verbose_name='Data Collected'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='data_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Data & Error Analysis'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='discussion',
            field=models.TextField(blank=True, null=True, verbose_name='Discussion'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='draft_used',
            field=models.OneToOneField(blank=True, help_text='Draft that was used to submit this report, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_report', to='QuestionBank.experimentdraft'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='group_members',
            field=models.TextField(blank=True, help_text='List of group members who participated', null=True, verbose_name='Group Members'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Objective/Aim'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='observation',
            field=models.TextField(verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='procedure',
            field=models.TextField(blank=True, null=True, verbose_name='Procedure/Method'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='experiment_reports/', verbose_name='Attach Report File'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='results',
            field=models.TextField(blank=True, null=True, verbose_name='Results/Raw Data'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='experimentreport',
            name='theory',
            field=models.TextField(blank=True, null=True, verbose_name='Theory/Introduction'),
        ),
    ]
