# Generated by Django 4.2 on 2025-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0020_reportevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentreport',
            name='graph_x_values',
            field=models.TextField(blank=True, help_text='Comma-separated list of X values (e.g., 1, 2, 3, 4)', null=True, verbose_name='X-Axis Values'),
        ),
        migrations.AddField(
            model_name='experimentreport',
            name='graph_y_values',
            field=models.TextField(blank=True, help_text='Comma-separated list of Y values (e.g., 10, 20, 30, 40)', null=True, verbose_name='Y-Axis Values'),
        ),
    ]
